[project]
name = "instagramdmscraper-master"
version = "0.1.0"
description = "Instagram DM's Scrapper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "termcolor>=3.1.0",
]
